-- ═══════════════════════════════════════════════════════════════
-- V1__init.sql
-- Initial schema for Job AI Application Agent
-- Managed by Flyway — do NOT edit this file after it has run.
-- Create a new Vn__ migration for changes.
-- ═══════════════════════════════════════════════════════════════

-- ── Extensions ──────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

-- ── Enum Types ───────────────────────────────────────────────────
CREATE TYPE application_status AS ENUM (
    'PENDING',
    'APPLIED',
    'UNDER_REVIEW',
    'INTERVIEW_SCHEDULED',
    'INTERVIEWED',
    'OFFER_RECEIVED',
    'REJECTED',
    'WITHDRAWN'
);

CREATE TYPE job_source AS ENUM (
    'LINKEDIN',
    'NAUKRI',
    'FOUNDIT',
    'INDEED',
    'WELLFOUND',
    'GREENHOUSE',
    'LEVER',
    'COMPANY_CAREER_PAGE',
    'OTHER'
);

-- ── user_profiles ────────────────────────────────────────────────
-- Mirrors the Firebase user. firebase_uid is the authoritative identity.
CREATE TABLE user_profiles (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    firebase_uid    VARCHAR(128) NOT NULL UNIQUE,
    email           VARCHAR(320) NOT NULL UNIQUE,
    full_name       VARCHAR(255),
    phone           VARCHAR(20),
    linkedin_url    VARCHAR(500),
    github_url      VARCHAR(500),
    portfolio_url   VARCHAR(500),
    college_name    VARCHAR(255),
    degree          VARCHAR(100),
    branch          VARCHAR(100),
    graduation_year SMALLINT,
    cgpa            NUMERIC(4,2),
    city            VARCHAR(100),
    expected_salary_min INTEGER,
    expected_salary_max INTEGER,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_profiles_firebase_uid ON user_profiles(firebase_uid);
CREATE INDEX idx_user_profiles_email        ON user_profiles(email);

-- ── candidate_skills ─────────────────────────────────────────────
CREATE TABLE candidate_skills (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    skill_name      VARCHAR(100) NOT NULL,
    category        VARCHAR(50),   -- BACKEND, FRONTEND, DATABASE, TOOL, CLOUD
    proficiency     VARCHAR(20),   -- BEGINNER, INTERMEDIATE, ADVANCED
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_candidate_skills_user_id ON candidate_skills(user_id);

-- ── candidate_projects ───────────────────────────────────────────
CREATE TABLE candidate_projects (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    project_name    VARCHAR(255) NOT NULL,
    description     TEXT,
    tech_stack      VARCHAR(500),  -- comma-separated
    github_url      VARCHAR(500),
    live_url        VARCHAR(500),
    start_date      DATE,
    end_date        DATE,
    is_featured     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_candidate_projects_user_id ON candidate_projects(user_id);

-- ── candidate_certifications ─────────────────────────────────────
CREATE TABLE candidate_certifications (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    cert_name       VARCHAR(255) NOT NULL,
    issuer          VARCHAR(255),
    issue_date      DATE,
    expiry_date     DATE,
    credential_url  VARCHAR(500),
    credential_id   VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_candidate_certifications_user_id ON candidate_certifications(user_id);

-- ── jobs ─────────────────────────────────────────────────────────
CREATE TABLE jobs (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id         VARCHAR(500),          -- platform-specific job ID
    source              job_source  NOT NULL,
    job_title           VARCHAR(255) NOT NULL,
    company_name        VARCHAR(255) NOT NULL,
    location            VARCHAR(255),
    is_remote           BOOLEAN     NOT NULL DEFAULT FALSE,
    job_description     TEXT,
    required_skills     TEXT,                  -- comma-separated
    preferred_skills    TEXT,
    experience_min      SMALLINT,
    experience_max      SMALLINT,
    salary_min          INTEGER,
    salary_max          INTEGER,
    salary_currency     VARCHAR(10) DEFAULT 'INR',
    application_url     VARCHAR(1000),
    source_url          VARCHAR(1000),
    match_score         NUMERIC(4,2),          -- 0.00–10.00
    is_rejected         BOOLEAN     NOT NULL DEFAULT FALSE,
    rejection_reason    TEXT,
    ai_analysis         JSONB,                 -- full AI analysis object
    posted_at           TIMESTAMPTZ,
    scraped_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_jobs_source        ON jobs(source);
CREATE INDEX idx_jobs_match_score   ON jobs(match_score DESC);
CREATE INDEX idx_jobs_is_rejected   ON jobs(is_rejected);
CREATE INDEX idx_jobs_scraped_at    ON jobs(scraped_at DESC);
CREATE INDEX idx_jobs_company_name  ON jobs(company_name);
-- Prevent duplicate jobs from same platform
CREATE UNIQUE INDEX idx_jobs_external_id_source ON jobs(external_id, source)
    WHERE external_id IS NOT NULL;

-- ── resume_versions ──────────────────────────────────────────────
CREATE TABLE resume_versions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    job_id          UUID        REFERENCES jobs(id) ON DELETE SET NULL,
    version_label   VARCHAR(100),              -- e.g., "Java Full Stack v3"
    html_content    TEXT,                      -- HTML source for PDF rendering
    pdf_path        VARCHAR(500),              -- relative path to generated PDF
    keywords_used   TEXT,                      -- ATS keywords injected
    ats_score       NUMERIC(4,2),
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_resume_versions_user_id ON resume_versions(user_id);
CREATE INDEX idx_resume_versions_job_id  ON resume_versions(job_id);

-- ── cover_letters ────────────────────────────────────────────────
CREATE TABLE cover_letters (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    job_id          UUID        REFERENCES jobs(id) ON DELETE SET NULL,
    content         TEXT        NOT NULL,
    pdf_path        VARCHAR(500),
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cover_letters_user_id ON cover_letters(user_id);
CREATE INDEX idx_cover_letters_job_id  ON cover_letters(job_id);

-- ── applications ─────────────────────────────────────────────────
CREATE TABLE applications (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID            NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    job_id              UUID            NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    resume_version_id   UUID            REFERENCES resume_versions(id) ON DELETE SET NULL,
    cover_letter_id     UUID            REFERENCES cover_letters(id) ON DELETE SET NULL,
    status              application_status NOT NULL DEFAULT 'PENDING',
    applied_at          TIMESTAMPTZ,
    interview_date      TIMESTAMPTZ,
    offer_amount        INTEGER,
    notes               TEXT,
    playwright_session  JSONB,                 -- automation session metadata
    screenshot_paths    TEXT,                  -- comma-separated screenshot paths
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, job_id)                    -- prevent duplicate applications
);

CREATE INDEX idx_applications_user_id ON applications(user_id);
CREATE INDEX idx_applications_job_id  ON applications(job_id);
CREATE INDEX idx_applications_status  ON applications(status);

-- ── application_status_history ───────────────────────────────────
CREATE TABLE application_status_history (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id  UUID            NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    from_status     application_status,
    to_status       application_status NOT NULL,
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT
);

CREATE INDEX idx_status_history_application_id ON application_status_history(application_id);

-- ── audit trigger function ────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply audit trigger to tables with updated_at
CREATE TRIGGER trg_user_profiles_updated_at
    BEFORE UPDATE ON user_profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_applications_updated_at
    BEFORE UPDATE ON applications
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
